/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

import static java.lang.System.exit;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {

        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public JMenuItem getMnuresoluciones() {
        return mnuresoluciones;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuUsuarios = new javax.swing.JMenuItem();
        Menu = new javax.swing.JMenu();
        mnuresoluciones = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnutotales = new javax.swing.JMenuItem();
        mnurpttotales = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FrmInterno"); // NOI18N
        setUndecorated(true);

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Registros");
        jMenu1.add(jSeparator1);

        mnuUsuarios.setText("Usuarios");
        jMenu1.add(mnuUsuarios);

        menuBar.add(jMenu1);

        Menu.setText("Resoluciones");

        mnuresoluciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuresoluciones.setText("Resoluciones");
        mnuresoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuresolucionesActionPerformed(evt);
            }
        });
        Menu.add(mnuresoluciones);

        menuBar.add(Menu);

        jMenu3.setText("Estadisticas");

        mnutotales.setText("Totales");
        mnutotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnutotalesActionPerformed(evt);
            }
        });
        jMenu3.add(mnutotales);

        mnurpttotales.setText("Reporte Totales");
        jMenu3.add(mnurpttotales);

        menuBar.add(jMenu3);

        jMenu4.setText("Salir");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuresolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuresolucionesActionPerformed
        // TODO add your handling code here:
        FrmResoluciones frm1 = new FrmResoluciones();
        frm1.setVisible(true);

    }//GEN-LAST:event_mnuresolucionesActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Desea salir de la aplicación", "Realmente desea salir", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            exit(0);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnutotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnutotalesActionPerformed
        FrmResumen frmResumen = new FrmResumen();
        frmResumen.setVisible(true);
    }//GEN-LAST:event_mnutotalesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Menu;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenuItem mnuUsuarios;
    public javax.swing.JMenuItem mnuresoluciones;
    public javax.swing.JMenuItem mnurpttotales;
    public javax.swing.JMenuItem mnutotales;
    // End of variables declaration//GEN-END:variables

}
